spring.datasource.url=jdbc:postgresql://localhost:54322/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:54321/auth/v1/keys