spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://woggjhauuhpatfescous.supabase.co/auth/v1/.well-known/jwks.json

cors.allowed-origins=http://localhost:5173

